# Big 5 KMeans example

## Import the relevant libraries

In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# Set the styles to Seaborn
sns.set()
# Import the KMeans module so we can perform k-means clustering with sklearn
from sklearn.cluster import KMeans

## Load the data

In [10]:
# Load the data
#We have taken already cleaned data
data = pd.read_csv ('questionairre_rating.csv')

In [21]:
# Check what's inside
data.describe()

,EXT1,EXT2,EXT3,EXT4,EXT5,EXT6,EXT7,EXT8,EXT9,EXT10,...,OPN1,OPN2,OPN3,OPN4,OPN5,OPN6,OPN7,OPN8,OPN9,OPN10
count,874366.000000,874366.000000,874366.000000,874366.000000,874366.000000,874366.000000,874366.000000,874366.000000,874366.000000,874366.000000,...,874366.000000,874366.000000,874366.00000,874366.000000,874366.000000,874366.000000,874366.000000,874366.000000,874366.000000,874366.000000
mean,2.645722,2.795878,3.298991,3.167780,3.297526,2.411209,2.780486,3.443966,2.979552,3.588271,...,3.703012,2.070539,4.03500,1.995500,3.824292,1.901216,4.022253,3.221338,4.166729,3.983932
std,1.250873,1.306719,1.188253,1.210437,1.239671,1.208842,1.380443,1.242380,1.325272,1.274354,...,1.100085,1.095057,1.04003,1.071263,0.933457,1.084801,0.935575,1.222729,0.971584,0.986200
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,2.000000,2.000000,2.000000,2.000000,2.000000,1.000000,2.000000,2.000000,2.000000,3.000000,...,3.000000,1.000000,3.00000,1.000000,3.000000,1.000000,4.000000,2.000000,4.000000,3.000000
50%,3.000000,3.000000,3.000000,3.000000,3.000000,2.000000,3.000000,4.000000,3.000000,4.000000,...,4.000000,2.000000,4.00000,2.000000,4.000000,2.000000,4.000000,3.000000,4.000000,4.000000
75%,4.000000,4.000000,4.000000,4.000000,4.000000,3.000000,4.000000,4.000000,4.000000,5.000000,...,5.000000,3.000000,5.00000,3.000000,5.000000,2.000000,5.000000,4.000000,5.000000,5.000000
max,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,...,5.000000,5.000000,5.00000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000

In [13]:
#We ignore country for our analysis right now
data = data.drop('country', axis = 1)
data.head()

,EXT1,EXT2,EXT3,EXT4,EXT5,EXT6,EXT7,EXT8,EXT9,EXT10,...,OPN1,OPN2,OPN3,OPN4,OPN5,OPN6,OPN7,OPN8,OPN9,OPN10
0,4.0,1.0,5.0,2.0,5.0,1.0,5.0,2.0,4.0,1.0,...,5.0,1.0,4.0,1.0,4.0,1.0,5.0,3.0,4.0,5.0
1,3.0,5.0,3.0,4.0,3.0,3.0,2.0,5.0,1.0,5.0,...,1.0,2.0,4.0,2.0,3.0,1.0,4.0,2.0,5.0,3.0
2,2.0,3.0,4.0,4.0,3.0,2.0,1.0,3.0,2.0,5.0,...,5.0,1.0,2.0,1.0,4.0,2.0,5.0,3.0,4.0,4.0
3,2.0,2.0,2.0,3.0,4.0,2.0,2.0,4.0,1.0,4.0,...,4.0,2.0,5.0,2.0,3.0,1.0,4.0,4.0,3.0,3.0
4,3.0,3.0,3.0,3.0,5.0,3.0,3.0,5.0,3.0,4.0,...,5.0,1.0,5.0,1.0,5.0,1.0,5.0,3.0,5.0,5.0

## Clustering and Elbow method

In [16]:
# Createa an empty list
wcss =[]

# Create all possible cluster solutions with a loop
# We have chosen to get solutions from 1 to 9 clusters; you can ammend that if you wish
for i in range(1,10):
    # Clsuter solution with i clusters
    kmeans = KMeans(i)
    # Fit the STANDARDIZED data
    kmeans.fit(x)
    # Append the WCSS for the iteration
    wcss.append(kmeans.inertia_)
    
# Check the result
wcss

[61216504.768144906,
 54725693.457850404,
 51855626.0834198,
 49909416.20964354,
 48508345.600263305,
 47597089.88289606,
 46728945.7992968,
 46008087.12396816,
 45390346.80552374]

In [1]:
# Plot the number of clusters vs WCSS
plt.plot(range(1,10),wcss)
# Name your axes
plt.xlabel('Number of clusters')
plt.ylabel('WCSS')

NameError: name 'plt' is not defined

## Explore clustering solutions and select the number of clusters

In [18]:
# WE see elbow at 5
kmeans_new = KMeans(5)
# Fit the data
kmeans_new.fit(x)
# Create a new data frame with the predicted clusters
clusters = x.copy()
clusters['cluster_pred'] = kmeans_new.fit_predict(x)

In [26]:
# Check if everything seems right
clusters

SyntaxError: expression cannot contain assignment, perhaps you meant "=="? (<ipython-input-26-5300b952959d>, line 2)